### ISSUE TITLE
Try to solve the weird ?? sometimes purple text ?? from certain animals

### ISSUE THREAD

**Issue by aedobbyn** [revodavid/rlangtip#44]

**Comment by revodavid** [comment]
Added `color` option to `rtip`, defaults to FALSE for now

**Comment by aedobbyn** [comment]
This fixed in https://github.com/aedobbyn/multicolor/commit/89ddc68a5cedf2795c94a600b1c63be981a8f3df#diff-66008b874b62442e0a963d51521666dbR261, I'll let you know when it's up on CRAN :)

The problem was that the close tag wasn't applied at the end of the purple characters when the line of dashes was too short (so you were right about that!), so the open tag applied purple to all following characters in the absence of a different opening color tag.

**Comment by aedobbyn** [comment]
@revodavid the fix in `multicolor` is on its way to CRAN at the moment. If you want to change the default `color` value to `TRUE` that should now be fine.
