### ISSUE TITLE
Function to return table of tips

### ISSUE THREAD

**Issue by revodavid** [revodavid/rlangtip#47]
Unexported function for editor use, to get the list of tips as a tibble

**Comment by aedobbyn** [comment]
Returning a sample of popular tweets in https://github.com/revodavid/rlangtip/blob/b256b4817f142a9505bc3d2118c477cc1a94baed/R/run_pipleine.R#L31

**Comment by aedobbyn** [comment]
Closed in https://github.com/revodavid/rlangtip/commit/a38f6bad7a2f7c5622f867d0ad8137949f4b9025#diff-9250e0759be09712b47ecd6796660d90R29
